### ISSUE TITLE
Loading Kytos Napps in non-deterministic order can leads to error

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/kytos#163]
Kytos loads the Napps based on the result of `NAppsManager.get_napps_from_path()`, which is based on `Pathlib.glob()` (https://github.com/kytos-ng/kytos/blob/master/kytos/core/napps/manager.py#L198-L204 called from [controller start process](https://github.com/kytos-ng/kytos/blob/master/kytos/core/controller.py#L871-L879)). There are some discussions surrounding the order which `Pathlib.glob()` returns its objects, which seems to be a non-deterministic way (https://bugs.python.org/issue38764). As a result we have the list of Napps ordered in a non quite useful way:

```
>>> from kytos.core.napps import NApp, NAppsManager
>>> from pathlib import Path
>>> NAppsManager.get_napps_from_path(Path("/var/lib/kytos/napps/"))
[NApp(kytos/of_core), NApp(kytos/flow_manager), NApp(kytos/topology), NApp(kytos/mef_eline), NApp(kytos/of_lldp), NApp(kytos/pathfinder), NApp(kytos/storehouse), NApp(kytos/maintenance)]
```

We can also see this behavior from Kytos logs concerning the Napps loading process:

```
Jan 18 02:21:25 c618340fa1db kytos.core.controller:INFO controller:268:  Starting Kytos - Kytos Controller
Jan 18 02:21:25 c618340fa1db kytos.core.controller:INFO controller:875:  Loading NApp kytos/of_core
Jan 18 02:21:26 c618340fa1db kytos.core.controller:INFO controller:875:  Loading NApp kytos/flow_manager
Jan 18 02:21:27 c618340fa1db kytos.core.controller:INFO controller:875:  Loading NApp kytos/topology
Jan 18 02:21:27 c618340fa1db kytos.core.controller:INFO controller:875:  Loading NApp kytos/mef_eline
Jan 18 02:21:36 c618340fa1db kytos.core.controller:INFO controller:875:  Loading NApp kytos/of_lldp
Jan 18 02:21:36 c618340fa1db kytos.core.controller:INFO controller:875:  Loading NApp kytos/pathfinder
Jan 18 02:21:38 c618340fa1db kytos.core.controller:INFO controller:875:  Loading NApp kytos/storehouse
Jan 18 02:21:39 c618340fa1db kytos.core.controller:INFO controller:875:  Loading NApp kytos/maintenance
```

Two examples of impacts the wrong order has on the Napps are shown below:

```
Jan 18 02:21:32 c618340fa1db kytos.napps.kytos/flow_manager:ERROR storehouse:47:  Error retrieving persistence box from storehouse.
Jan 18 02:21:32 c618340fa1db kytos.napps.kytos/flow_manager:DEBUG main:469:  There are no flows to load: Error retrieving persistence box from storehouse.
Jan 18 02:21:34 c618340fa1db kytos.napps.kytos/topology:ERROR main:202:  Fail to load network status from storehouse: Error retrieving persistence box from storehouse.
```

In the first case, FlowManager couldn't load the stored flows due to an error retrieving data from the storehouse. The second one, Topology could not load the topology.

There are many possible ways of fixing/workaround the above situation:
1. Implement some sort of dependency management for Kytos Napps. This would be the ideal solution. We can leverage Networkx library to create a dependency graph using `kytos.json` attribute named `napp_dependencies` (using an approach similar to discussed in https://www.thebookofjoel.com/networkx-dependencies-python). Or we can have a more "standalone" solution (and still simple), based on topological sorting algorithms (such as Kahn algorithm described in https://en.wikipedia.org/wiki/Topological_sorting#Algorithms).
2. Implement some sort of order based on numbers (similar to what we used to have in Linux sysvinit mechanism with the `/etc/rcX.d/Snn` (where nn would be the startup order)). Then we can have something like: renaming the enabled link for a Napp to its actually startup order such as  `/var/lib/kytos/napps/kytos/005_storehouse` and `/var/lib/kytos/napps/kytos/005_of_core` and so on. Of course, we have to change `NAppsManager.get_napps_from_path()` so it can returns Napps in alphabetical order. Another point is that Napp's developer can express his/her desired startup order in some attribute on the kytos.json file (e.g., `"startup_order": "005"`, defaults to "999").
3. Implement some sort of order based on file creation/modification timestamp, so that we can respect the same order in which Napps were installed (and consequently `kytos.json` file was created/modified). Then, if the Operator/Admin installed a Napp and its dependencies were installed before, the dependencies will be loaded first.  Of course, we also have to change `NAppsManager.get_napps_from_path()` accordingly.

**Comment by italovalcy** [comment]
One example for the workaround proposed at suggestion 3 above is shown below:

```
>>> from pathlib import Path
>>> p = Path("/var/lib/kytos/napps/")
>>> sorted(p.glob("*/*/kytos.json"), key=lambda f: f.stat().st_mtime)
[PosixPath('/var/lib/kytos/napps/kytos/storehouse/kytos.json'), PosixPath('/var/lib/kytos/napps/kytos/of_core/kytos.json'), PosixPath('/var/lib/kytos/napps/kytos/flow_manager/kytos.json'), PosixPath('/var/lib/kytos/napps/kytos/topology/kytos.json'), PosixPath('/var/lib/kytos/napps/kytos/of_lldp/kytos.json'), PosixPath('/var/lib/kytos/napps/kytos/pathfinder/kytos.json'), PosixPath('/var/lib/kytos/napps/kytos/mef_eline/kytos.json'), PosixPath('/var/lib/kytos/napps/kytos/maintenance/kytos.json')]
```

Besides the fact that the above order will bring a more deterministic output and with the proper order (i.e., the order in which Napps were installed according to the Dockerfile https://github.com/amlight/kytos-docker/blob/master/Dockerfile#L36-L45), it can be actually modified by the admin/operator by just changing the modification timestamp of the file. Thus, let's say that we wanna have the maintenance loading before mef_eline, we can just do:
```
>>> import os
>>> os.system("touch /var/lib/kytos/napps/kytos/mef_eline/kytos.json")
>>> sorted(p.glob("*/*/kytos.json"), key=lambda f: f.stat().st_mtime)
[PosixPath('/var/lib/kytos/napps/kytos/storehouse/kytos.json'), PosixPath('/var/lib/kytos/napps/kytos/of_core/kytos.json'), PosixPath('/var/lib/kytos/napps/kytos/flow_manager/kytos.json'), PosixPath('/var/lib/kytos/napps/kytos/topology/kytos.json'), PosixPath('/var/lib/kytos/napps/kytos/of_lldp/kytos.json'), PosixPath('/var/lib/kytos/napps/kytos/pathfinder/kytos.json'), PosixPath('/var/lib/kytos/napps/kytos/maintenance/kytos.json'), PosixPath('/var/lib/kytos/napps/kytos/mef_eline/kytos.json')]
```

Of course, this would be a workaround, while a more robust solution it's been designed and extensively tested (such as suggestion 1 or 2).

**Comment by ajoaoff** [comment]
@italovalcy thanks for raising this issue with possible solutions. It is a problem that has been raised sometimes in the past, but a solution has never been really discussed.

**Comment by viniarck** [comment]
Agreed @italovalcy, the workaround is a great, thanks for reporting and proposing the solutions, I think it's sufficient for the main use cases, especially if docker build is considered the canonical deployment recommended approach. Regarding the other proposed solutions, the graph dependency resolution approach sounds great to have in the future.

**Comment by viniarck** [comment]
This landed on https://github.com/kytos-ng/kytos/pull/167
