### ISSUE TITLE
Blueprint for OpenFlow multi-table pipeline processing

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/kytos#186]
OpenFlow Multi-table pipeline processing (adjustments on mef-eline, of-lldp, coloring. INT needs this feature.

- mef_eline which table should it write it to?
- of_lldp which table should it write it to?
- coloring which table should it write it to?
- it was also discussed an idea of a potential napp to push and install flows to one table to other ones, needs to discuss if needed and the benefits

**Comment by viniarck** [comment]
If table if different than 0, then it's also desirable how to enable that how flows from table 0 to another table.

**Comment by Alopalao** [comment]
Moving this discussion to [here](https://github.com/kytos-ng/kytos/discussions/343)

**Comment by viniarck** [comment]
Landed on https://github.com/kytos-ng/kytos/pull/359
