### ISSUE TITLE
No mailing list

### ISSUE THREAD

**Issue by ajoaoff** [kytos-ng/kytos#23]
Original issue opened by @cemsbr at https://github.com/kytos/kytos/issues/524.

- http://lists.kytos.io/pipermail/community/ loads for a long time before failing
- https://lists.kytos.io/pipermail/community/ has no archives

**Comment by viniarck** [comment]
Kytos-ng at the moment doesn't have a mailing list, we're only maintaining a Slack channel. One day we might have a mailing list again.
