### ISSUE TITLE
`connection_timeout` default config missing from `KytosConfig`

### ISSUE THREAD

**Issue by Ktmi** [kytos-ng/kytos#275]
Attempting to use `kytos.conf` configuration files from older versions results in an error due to a missing connection_timeout value. For most if not all configuration values, a default value is set in `KytosConfig`. Perhaps this issue can be stopped from recurring in the future, by reading the template document to get the default configs, instead of relying on programmers adding in the definition directly to `KytosConfig`.

**Comment by viniarck** [comment]
@Ktmi good catch. Yes, currently it can be a bit error prone and lead to situations that you've just caught. This is a great idea, let's  map a new issue to read the default settings from the template and set the defaults based on that and then making sure that all interpolations work as intended too. I'll submit a new patch for this bumping a new version, making sure it's still compatible with older configuration file is something that kytos-ng should cover.
