### ISSUE TITLE
`pythonpackage.yml` CI build test sometimes gets stuck

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/kytos#289]
[./github/workflows/pythonpackage.yml](./github/workflows/pythonpackage.yml) CI build test sometimes gets stuck, @gretelliz spotted his on PR #278 :

![20221004_122024](https://user-images.githubusercontent.com/1010796/193860289-f2cbace4-f69b-4353-90a9-dde332d1f0a8.png)

This was marked as required, it's desirable to still have the build `sdist` being tested, but we need this to work deterministically. This is a minor fix that we should prioritize in a next opportunity. `sdist` build is specially important as a prerequisite when we also prioritize publishing this to pypi #271

**Comment by viniarck** [comment]
Running it locally it succeeds, including other PRs that also passed 

```
❯ python setup.py sdist bdist_wheel
running sdist
running egg_info
Installing dependencies...
```

Looks like the issue was that apparently it had a prior job definition stuck with py3.6, I removed it, if it doesn't show up anymore then we can close this issue.

**Comment by gretelliz** [comment]
Fine, it seems that was the problem.
