### ISSUE TITLE
Blueprint to support OF table stats and consider evolving `flow_stats` into `kytos_stats`

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/kytos#330]
This is a blueprint to support OF table stats and consider evolving `flow_stats` into `kytos_stats`

![20230208_152702](https://user-images.githubusercontent.com/1010796/217619454-d0ef9e00-8b80-45ac-9e24-c7c3d7fa5055.png)

https://opennetworking.org/wp-content/uploads/2014/10/openflow-spec-v1.3.0.pdf

- Similarly to how flow stats are being exposed, we'd like to have table stats exposed in REST endpoints.
- Can we evolve `flow_stats` into `kytos_stats`? We want to have a single NApp responsible to deal with OF stats.
- In the future, we'd like evolve it to support other type of time series stats like number of EVCs, number of switches, number of interfaces, links, controller uptime.

**Comment by gretelliz** [comment]
Discussions [here](https://github.com/kytos-ng/kytos/discussions/349)
