### ISSUE TITLE
Add in `status_reason` and `register_status_reason_func` to Switches, Links, and Interfaces

### ISSUE THREAD

**Issue by Ktmi** [kytos-ng/kytos#383]
In order to comply with the blueprint added by kytos-ng/kytos#356, Switches, Links, and Interfaces should have the `status_reason` property and the `register_status_reason_func` method added to them. These will allow for NApps to provide more detailed information on why a device is not in the `EntityStatus.UP` state.

**Comment by viniarck** [comment]
Landed on https://github.com/kytos-ng/kytos/pull/384
