### ISSUE TITLE
Add GH template to all kytos-ng repos

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/kytos#444]
To minimize trivial back and forth regarding PR description contents, let's add [this template](https://kytos-ng.github.io/procedures/prs.html#submitting-a-pr) for all Kytos-ng repos

**Comment by Ktmi** [comment]
We can add in the templates through adding `.github` repo to our organization. At least thats what I understand we can do according to this https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file
