### ISSUE TITLE
"List EVCs" shows the Switch information as "dpid" instead of "node_name" randomly

### ISSUE THREAD

**Issue by RenataFrez** [kytos-ng/kytos#481]
In the Kytos Web UI, after listing all EVCs using the option "List EVCs", the Switch information sometimes shows the "dpid" and sometimes "node_name." 

We couldn't reproduce this issue, which seems random. I tried changing the "Switch Labels" for "name" and "description," but it just changed the information in the map, not in the EVCs list. 

From the operation perspective, it is better to show the switch information using its "node_name."

**Comment by viniarck** [comment]
Landed on version `2024.1`. Linked PR https://github.com/kytos-ng/mef_eline/pull/494

Thanks for reporting it, @RenataFrez
