### ISSUE TITLE
Add new columns in the "View Connections by kytos/mef_eline"

### ISSUE THREAD

**Issue by RenataFrez** [kytos-ng/kytos#482]
The "View Connections by kytos/mef_eline" could have two new columns to help identify the EVCs path behavior:

1. Column with the "dynamic_backup_path" tag value for all the EVCs.
2. Column showing if an EVC has fixed paths or not.

**Comment by viniarck** [comment]
@RenataFrez thanks for the feature request, good to know this can be helpful. I've moved this issue to mef_eline repo https://github.com/kytos-ng/mef_eline/issues/594 eventually it'll get picked up feel free to assign the priority there just so it can get planned and included in a next version.
