### ISSUE TITLE
`syslog` is no longer installed by default in Debian 12+

### ISSUE THREAD

**Issue by Alopalao** [kytos-ng/kytos#486]
Debian does not longer come with `syslog`. It instead is using `journalctl`. We recently have adopted Debian 12 as the to go Linux distribution for our environment setup [tutorial](https://github.com/kytos-ng/documentation/blob/master/tutorials/napps/development_environment_setup.rst). This means that any `log.debug()` message will not be stored to be analyzed later. To use `log.debug()` we would need to adapt Kytos to use `journalctl` or install `syslog` in our environments (probably add its installation process or a recommendation in the tutorial).

Something to notice is that this move is because of the embracing `systemd` as default as it works tightly with `journalctl`. Many linux distributions has moved to `systemd` already thus `journalctl` is already well adopted.

**Comment by viniarck** [comment]
Anything else remaining that needs to be updated in the [dev env tutorial](https://github.com/kytos-ng/documentation/blob/master/tutorials/napps/development_environment_setup.rst)? @Alopalao, wondering when we can close this issue.

**Comment by Alopalao** [comment]
Nothing else is needed. This issue can be closed.
