### ISSUE TITLE
chore: refactor `log.info`` "Limited reached`" as `"Limit reached"`

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/kytos#498]
I just realized that one `"Limited reached"` log entry remained:

https://github.com/kytos-ng/kytos/blob/master/kytos/core/pacing.py#L170

On PR https://github.com/kytos-ng/kytos/pull/497 this log entry was supposed to be refactored, but this has been left behind unexpectedly. This is a very cosmetic/trivial thing, but since this log message is so helpful for grepping in the logs it's great to have it fixed too and normalized. @Ktmi can you send a quick PR? It's up to you if you wish to send a new patch or just a new PR without bumping the version and then you retag/re-release `2024.1.1` again, since this is pretty recent it's ok to do it.

**Comment by Ktmi** [comment]
@viniarck Oh, I refactored that already in the previous PR.
