### ISSUE TITLE
Create in Auth module a timeout to resolve response when it is not received from Storehouse

### ISSUE THREAD

**Issue by ajoaoff** [kytos-ng/kytos#79]
Original issue opened by @gleybersonandrade at https://github.com/kytos/kytos/issues/981.

When the Auth module was created, a while loop was used to wait for the response from the Storehouse, but if it is not received, an infinite loop can occur.

```
while True:
      time.sleep(0.1)
      if response:
            break
```

We have to find a method to create a timeout or something like this to resolve the response when it is not received.

**Comment by viniarck** [comment]
This no longer applies. On core `Auth` is now backed by MongoDB `users` collection.
